# fly.toml app configuration file generated for lotto-filter-api-psd on 2026-02-27T19:51:29+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lotto-filter-api-psd'
primary_region = 'icn'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
